#ifndef BOARD_H
#define BOARD_H

typedef enum {
	NONE = 0,
	PAWN = 1,
	KNIGHT = 2,
	BISHOP = 3,
	ROOK = 4,
	QUEEN = 5,
	KING = 6,
	WHITE = 8,
	BLACK = 16,
	WHITE_PAWN = PAWN | WHITE,
	WHITE_KNIGHT = KNIGHT | WHITE,
	WHITE_BISHOP = BISHOP | WHITE,
	WHITE_ROOK = ROOK | WHITE,
	WHITE_QUEEN = QUEEN | WHITE,
	WHITE_KING = KING | WHITE,
	BLACK_PAWN = PAWN | BLACK,
	BLACK_KNIGHT = KNIGHT | BLACK,
	BLACK_BISHOP = BISHOP | BLACK,
	BLACK_ROOK = ROOK | BLACK,
	BLACK_QUEEN = QUEEN | BLACK,
	BLACK_KING = KING | BLACK
} Pieces;

typedef enum {
	WHITE_SIDE = 0,
	BLACK_SIDE = 1
} Side;

#endif